version: '3'

services:
  fabmanager:
    restart: always
    image: flcdf/fabmanager:2.4.6
    build:
      dockerfile: './Dockerfile'
      context: '..'
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - 3000
    environment:
      RAILS_ENV: production
      RACK_ENV: production
    env_file:
      - ${PWD}/config/env
    volumes:
      - ${PWD}/public/assets:/usr/src/app/public/assets
      - ${PWD}/public/uploads:/usr/src/app/public/uploads
      - ${PWD}/invoices:/usr/src/app/invoices
      - ${PWD}/exports:/usr/src/app/exports
      - ${PWD}/log:/var/log/supervisor
      - ${PWD}/plugins:/usr/src/app/plugins
    networks:
      - fabmanager-prod
  
  redis:
    restart: always
    image: redis:6-alpine
    volumes:
      - ${PWD}/redis:/data
    networks:         
      - fabmanager-prod

  elasticsearch:
    restart: always
    image: elasticsearch:5.6
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PWD}/elasticsearch/config:/usr/share/elasticsearch/config
      - ${PWD}/elasticsearch:/usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ${PWD}/elasticsearch/backups:/usr/share/elasticsearch/backups
    networks:         
      - fabmanager-prod

  postgres:
    image: postgres:9.6
    volumes:
     - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always  
    networks:         
      - fabmanager-prod

networks:
  fabmanager-prod:
